/*
 * Liste des chansons affichées sur la page d'accueil et dans le recueil, dans l'ordre.
 * Chaque identifiant correspond à un dossier `chansons/<id>/` contenant `chanson.js`.
 */
window.CATALOGUE = [
  "au-clair-de-la-lune",
  "frere-jacques",
  "ah-les-crocodiles",
  "une-souris-verte",
  "fais-dodo",
  "alouette",
  "petit-navire",
  "pont-avignon",
  "promenons-nous",
  "ainsi-font",
  "meunier-tu-dors",
  "dodo-l-enfant-do",
  "a-la-claire-fontaine",
  "une-poule-sur-un-mur",
  "savez-vous-planter-les-choux",
  "il-pleut-bergere",
  "pomme-de-reinette",
  "dans-la-foret-lointaine",
  "bateau-sur-l-eau",
  "mon-ane",
  "il-court-le-furet",
  "ah-vous-dirai-je-maman",
  "cadet-rousselle",
  "le-bon-roi-dagobert",
  "jean-petit-qui-danse",
  "il-etait-une-bergere",
  "nous-n-irons-plus-au-bois",
  "compere-guilleri",
  "dame-tartine",
  "en-passant-par-la-lorraine",
  "malbrough",
  "mon-beau-sapin",
];
